### ISSUE TITLE
gitlab_hashes.json本地都有了，为什么还要去get ?

### ISSUE THREAD

**Issue by wpf97** [XTeam-Wing/gitlab-version#1]
go run main.go -i https://gitlab.com/
[DBG] get https://raw.githubusercontent.com/XTeam-Wing/gitlab-version/master/gitlab_hashes.json
[ERR] get latest hash failed: Get "https://raw.githubusercontent.com/XTeam-Wing/gitlab-version/master/gitlab_hashes.json": dial tcp [::]:443: connect: connection refused
2023/05/25 22:40:55 Could not run gitlab version: Get "https://raw.githubusercontent.com/XTeam-Wing/gitlab-version/master/gitlab_hashes.json": dial tcp [::]:443: connect: connection refused

**Comment by XTeam-Wing** [comment]
已更新，支持本地json文件。默认是拉取github workflow自动更新的规则文件
